services:
  mysql:
    image: mysql:8.1
    container_name: generated-columns-example-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: generated_columns_example
    volumes:
      - ./docker/mysql:/var/lib/mysql
  postgres:
    image: postgres:15-alpine
    container_name: generated-columns-example-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: portgres
      POSTGRES_DB: generated_columns_example
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
